package pl.rzagorski.quizzstorm.data.api;

import javax.inject.Inject;

import pl.rzagorski.quizzstorm.model.api.ApiQuizExtendedModel;
import pl.rzagorski.quizzstorm.model.api.request.GetQuizDetailsRequest;
import pl.rzagorski.quizzstorm.model.api.request.GetQuizListRequest;
import pl.rzagorski.quizzstorm.model.api.response.GetQuizListResponse;
import rx.Observable;
import rx.functions.Func1;

/**
 * The API manager. Every function is built the same way:
 * <ol>
 *     <li>The function takes request model
 *     <li>Transforms model to the form acceptable by {@link ApiRequests}
 *     <li>Interacts with {@link ApiRequests} to get the model asynchroniously
 *     <li> Returns the model returned from API
 * </ol>
 *
 * Created by Robert Zagórski on 2016-07-21.
 */
public class ApiManager {

    /**
     * model generated by Retrofit2
     */
    private ApiRequests mApiRequests;

    @Inject
    public ApiManager(ApiRequests apiRequests) {
        mApiRequests = apiRequests;
    }

    public Observable<GetQuizListResponse> getQuizList(GetQuizListRequest quizListRequest) {
        return Observable.just(quizListRequest)
                .flatMap(new Func1<GetQuizListRequest, Observable<GetQuizListResponse>>() {
                    @Override
                    public Observable<GetQuizListResponse> call(GetQuizListRequest quizListRequest) {
                        Long startIndex = quizListRequest.getStartIndex();
                        Long endIndex = quizListRequest.getEndIndex();
                        return mApiRequests.getQizList(startIndex, endIndex);
                    }
                });
    }

    public Observable<ApiQuizExtendedModel> getQuizDetails(GetQuizDetailsRequest quizDetailsRequest) {
        return Observable.just(quizDetailsRequest)
                .flatMap(new Func1<GetQuizDetailsRequest, Observable<ApiQuizExtendedModel>>() {
                    @Override
                    public Observable<ApiQuizExtendedModel> call(GetQuizDetailsRequest quizDetailsRequest) {
                        Long quizId = quizDetailsRequest.getQuizId();
                        return mApiRequests.getQuizDetails(quizId);
                    }
                });
    }
}
