package pl.rzagorski.quizzstorm.model.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    private Long uid;
    private String name;
    private String nameEng;
    private String type;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, Long uid, String name, String nameEng, String type) {
        this.id = id;
        this.uid = uid;
        this.name = name;
        this.nameEng = nameEng;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNameEng() {
        return nameEng;
    }

    public void setNameEng(String nameEng) {
        this.nameEng = nameEng;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
