package pl.rzagorski.quizzstorm.model.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUIZ_RESULT".
 */
public class QuizResult {

    private Long id;
    private Long quiz;
    private Long city;
    private java.util.Date endDate;
    private Float result;
    private Long resolvedTime;

    public QuizResult() {
    }

    public QuizResult(Long id) {
        this.id = id;
    }

    public QuizResult(Long id, Long quiz, Long city, java.util.Date endDate, Float result, Long resolvedTime) {
        this.id = id;
        this.quiz = quiz;
        this.city = city;
        this.endDate = endDate;
        this.result = result;
        this.resolvedTime = resolvedTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQuiz() {
        return quiz;
    }

    public void setQuiz(Long quiz) {
        this.quiz = quiz;
    }

    public Long getCity() {
        return city;
    }

    public void setCity(Long city) {
        this.city = city;
    }

    public java.util.Date getEndDate() {
        return endDate;
    }

    public void setEndDate(java.util.Date endDate) {
        this.endDate = endDate;
    }

    public Float getResult() {
        return result;
    }

    public void setResult(Float result) {
        this.result = result;
    }

    public Long getResolvedTime() {
        return resolvedTime;
    }

    public void setResolvedTime(Long resolvedTime) {
        this.resolvedTime = resolvedTime;
    }

}
