package pl.rzagorski.quizzstorm.model.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUIZ_RATES".
 */
public class QuizRates {

    private Long id;
    private Long quiz;
    private Long rate;

    public QuizRates() {
    }

    public QuizRates(Long id) {
        this.id = id;
    }

    public QuizRates(Long id, Long quiz, Long rate) {
        this.id = id;
        this.quiz = quiz;
        this.rate = rate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQuiz() {
        return quiz;
    }

    public void setQuiz(Long quiz) {
        this.quiz = quiz;
    }

    public Long getRate() {
        return rate;
    }

    public void setRate(Long rate) {
        this.rate = rate;
    }

}
